### ISSUE TITLE
"cannot read property 'implementation' of undefined" error

### ISSUE THREAD

**Issue by DetachHead** [SwftAIO/TikTok-SSL-Pinning-Bypass#4]
```
> frida -U -f com.zhiliaoapp.musically --no-pause -l tiktoksslbypass.js
     ____
    / _  |   Frida 15.1.23 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Apple iPhone (id=xxx)
Spawned `com.zhiliaoapp.musically`. Resuming main thread!
TypeError: cannot read property 'implementation' of undefined
    at <eval> (/tiktoksslbypass.js:1)
[Apple iPhone::com.zhiliaoapp.musically ]-> Process terminated
```

iphone 6s ios 14 beta, jailbroken with checkra1n

**Comment by Muhand** [comment]
any luck with this?

**Comment by DetachHead** [comment]
nope i gave up

**Comment by Muhand** [comment]
After some digging, you need to downgrade to iOS 13. I haven't tested it out myself because it is a nightmare to downgrade to an unsigned version of iOS at this point (at least for me)

**Comment by volysandro** [comment]
Use my fork: https://github.com/volysandro/TikTok-SSL-Pinning-Bypass, I fixed it and made a PR but the author doesn't seem active.

**Comment by karak4n** [comment]
> Use my fork: https://github.com/volysandro/TikTok-SSL-Pinning-Bypass, I fixed it and made a PR but the author doesn't seem active.

I still get the error when using your version, IOS 15.8.3

![image](https://github.com/user-attachments/assets/6b97237e-f5d8-4be8-97f1-9296cc2d71d9)
